### ISSUE TITLE
Plans for .NET Standard support?

### ISSUE THREAD

**Issue by josephwoodward** [robertvazan/snappy.net#1]
Hi,

I'm just wondering if there are any plans for Snappy.NET to support .NET Standard. Is this something that you've looked at but found challenges? 

*Edit:* Ah, I've just found it'll depend on [this](https://github.com/robertvazan/crc32c.net/issues/1) which I *think* answers my question.

**Comment by robertvazan** [comment]
Indeed, there's a dependency on Crc32C.NET, but Snappy.NET also uses native libraries. It's either managed fallback only or building for a number of platforms. I would lean towards managed fallback only as it's easy to implement and guaranteed to work flawlessly.

**Comment by nzain** [comment]
netstandard supports pinvoke into native x86/x64 just like the full framework does. I've cloned your repository, but it doesn't compile... :-(

**Comment by robertvazan** [comment]
This library is no longer maintained. Feed free to adopt it if you find it useful.
