### ISSUE TITLE
Crc32C.NET assembly not resolved - Unity3D

### ISSUE THREAD

**Issue by mgstauffer** [robertvazan/snappy.net#2]
I'm trying Snappy.NET in my Unity3D project. I've got the package from NuGet and have added the NET 2.0 version to my Unity project. But I'm getting an error: 

"Assembly 'Assets/Plugins/Snappy.NET.dll' will not be loaded due to errors:
Unable to resolve reference 'Crc32C.NET'. Is the assembly missing or incompatible with the current platform?"

So I got Crc32C.NET from nuget as well (1.0.5.0) and dropped it in my Unity project, but the error is persisting.

**Comment by robertvazan** [comment]
Crc32C.NET is a dependency. NuGet should install it automatically. No idea what went wrong.

**Comment by mgstauffer** [comment]
I was doing a manual download and install of Snappy.NET as described here
is needed for unity:
https://docs.microsoft.com/en-us/visualstudio/cross-platform/unity-scripting-upgrade?view=vs-2019

Then when it said in unity that Crc32C.NET couldn't be found I got that too
from NuGet via manual download.

-M

**Comment by mgstauffer** [comment]
I've sorted it out. It's a unity thing when running in the editor. Dependency assemblies must be copied to the top-level project folder to be found.  If you like, I can write a short para to describe this for Unity users in your project doc.

**Comment by robertvazan** [comment]
Thanks for the resolution. If it's general unity stuff, then a link to an existing article would be sufficient here.
